"""Manifest schema — the corpus's provenance record.

One entry per retrieved file: where it came from, under what licence, when, and the SHA256 of
the exact bytes. This is the artifact the licence gate tests against, and the thing you point
at when asked "where did this text come from and were you allowed to use it".

The SHA256 matters beyond integrity checking. Sources move and get revised — an ISA spec is a
living document. Recording the hash of what was actually ingested means a later "the answer
cites Section 3.2 but the spec says something different" is answerable: you can tell whether
the corpus is stale or the citation is wrong.
"""

from __future__ import annotations

import datetime as dt
from pathlib import Path

import yaml
from pydantic import BaseModel, Field, model_validator

from ingestion.licences import assert_redistributable


class ManifestEntry(BaseModel):
    """One retrieved file."""

    source_id: str
    title: str
    doc_type: str
    publisher: str

    url: str
    s3_key: str
    filename: str

    licence: str
    licence_url: str | None = None

    retrieved_at: dt.datetime
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    size_bytes: int = Field(gt=0)
    pages: int | None = None

    notes: str = ""

    @model_validator(mode="after")
    def _must_be_redistributable(self) -> ManifestEntry:
        """The gate, enforced on the record itself rather than only at fetch time.

        A manifest is a durable artifact — it outlives the run that produced it, is read by
        M2/M3/M4, and is what an auditor would look at. Validating here means a hand-edited or
        corrupted manifest cannot introduce a non-redistributable entry the rest of the
        pipeline then trusts.

        **mode="after", not a field validator.** A field validator on `licence` sees only the
        fields declared BEFORE it — pydantic validates in declaration order — so
        `info.data["licence_url"]` is absent and OPEN-PUBLICATION is rejected for missing
        evidence it actually has. Reordering the fields would fix it too, and would leave a
        correctness property silently depending on the order of two lines in a class body.
        """
        assert_redistributable(self.licence, licence_url=self.licence_url)
        return self


class Manifest(BaseModel):
    generated_at: dt.datetime
    entries: list[ManifestEntry] = Field(default_factory=list)

    @property
    def total_pages(self) -> int:
        return sum(e.pages or 0 for e in self.entries)

    @property
    def total_bytes(self) -> int:
        return sum(e.size_bytes for e in self.entries)

    def by_doc_type(self) -> dict[str, list[ManifestEntry]]:
        out: dict[str, list[ManifestEntry]] = {}
        for e in self.entries:
            out.setdefault(e.doc_type, []).append(e)
        return out

    # ----------------------------------------------------------------- serialisation

    def to_yaml(self) -> str:
        return yaml.safe_dump(
            self.model_dump(mode="json"),
            sort_keys=False,
            allow_unicode=True,
            width=100,
        )

    @classmethod
    def from_yaml(cls, text: str) -> Manifest:
        return cls.model_validate(yaml.safe_load(text))

    def write(self, path: Path) -> None:
        path.write_text(self.to_yaml(), encoding="utf-8")

    @classmethod
    def read(cls, path: Path) -> Manifest:
        return cls.from_yaml(path.read_text(encoding="utf-8"))

    # ----------------------------------------------------------------- provenance doc

    def to_provenance_markdown(self) -> str:
        """Render the human-readable mirror committed as docs/PROVENANCE.md.

        Generated rather than hand-maintained. A provenance record that drifts from the
        manifest is worse than none, because it still reads as authoritative.
        """
        lines = [
            "<!-- GENERATED by `python -m ingestion --write-provenance`. Do not edit by hand. -->",
            "",
            "# SpecSage — Data Provenance",
            "",
            f"Generated {self.generated_at.isoformat(timespec='seconds')} from the ingestion "
            "manifest.",
            "",
            f"**{len(self.entries)} files** · {self.total_pages} pages · "
            f"{self.total_bytes / 1_048_576:.1f} MB",
            "",
            "## Policy",
            "",
            "**Verified-redistributable only.** Every document below carries a licence that",
            "explicitly permits redistribution with attribution, so source text may be quoted",
            "in answers. There is no index-only tier: a source whose licence cannot be resolved",
            "to something redistributable is not ingested at all, and fails the build if",
            "declared. See `ingestion/licences.py`.",
            "",
            "## Corpus",
            "",
            "| Source | Type | Licence | Retrieved | Files | Pages |",
            "|---|---|---|---|---|---|",
        ]

        by_source: dict[str, list[ManifestEntry]] = {}
        for e in self.entries:
            by_source.setdefault(e.source_id, []).append(e)

        for source_id in sorted(by_source):
            group = by_source[source_id]
            head = group[0]
            lic = f"[{head.licence}]({head.licence_url})" if head.licence_url else head.licence
            pages = sum(e.pages or 0 for e in group)
            lines.append(
                f"| [{head.title}]({head.url}) | {head.doc_type} | {lic} | "
                f"{head.retrieved_at.date()} | {len(group)} | {pages or '—'} |"
            )

        lines += [
            "",
            "## Integrity",
            "",
            "Every file records the SHA256 of the exact bytes ingested. Sources are living",
            "documents — an ISA spec gets revised — so the hash is what makes a later",
            '"the answer cites Section 3.2 but the spec says otherwise" answerable: it',
            "distinguishes a stale corpus from a wrong citation.",
            "",
            "| File | SHA256 | Bytes |",
            "|---|---|---|",
        ]
        for e in sorted(self.entries, key=lambda x: (x.source_id, x.filename)):
            lines.append(f"| `{e.s3_key}` | `{e.sha256}` | {e.size_bytes:,} |")

        lines += [
            "",
            "## Not in the public corpus",
            "",
            "Arm's Architecture Reference Manual is licensed for personal/development use only.",
            "It is never committed to git, never written to a bucket used by a public",
            "deployment, and is confined to the M11 private instance behind a Terraform",
            "guardrail that refuses to apply if that instance would receive public ingress.",
            "",
        ]
        return "\n".join(lines)
